### ISSUE TITLE
Unable to use :message.im 

### ISSUE THREAD

**Issue by markediez** [slack-ruby/slack-ruby-client#122]
Hello,

Thanks for pointing me to an example earlier. There was no bug, I just didn't notice that private channels were called groups. However I'm at a loss on how to check for a direct message event. In your starter.rb file It says I should just do

```ruby
client.do :message.im do |data|
     # Some code
end
```

However, I get a no method error

> undefined method `im' for :message:Symbol (NoMethodError)

To those having the same issue, my current work around is to check if the channel is in the hash of client.ims

```ruby
client.on :message do |data|
    if client.ims[data["channel"]] == nil
      puts "NOT A DM"
    else
      puts "A DM"
    end
end
```

**Comment by dblock** [comment]
That error is because `:message` is indeed a symbol and it doesn't have an `.im` method. If you want to have a symbol like that it would be `:"message.im"`:

```
$ irb
2.2.1 :001 > :"message.im"
 => :"message.im" 
2.2.1 :002 > 
```

But I don't think there's an event called `message.im`, where did you read that? There's definitely a `message` event and then you should be able to look at the event type or something else in `data` (like you do here) to determine what kind of message this is.

**Comment by dblock** [comment]
Closing this, @markediez reopen if this didn't help.
