### ISSUE TITLE
Does slack-ruby-client include a method I can use for verifying Slack event requests?

### ISSUE THREAD

**Issue by ndbroadbent** [slack-ruby/slack-ruby-client#238]
I've got the Events API working, and Slack is posting events to my server. I'm looking at the [Verifying Requests From Slack](https://api.slack.com/docs/verifying-requests-from-slack) documentation, and it doesn't mention Ruby under the "SDK support" section. Is that an oversight, or is there still no official way to verify Slack requests if you're using Ruby? I'm happy to follow the step-by-step instructions, but would prefer to use a library. Is there another Ruby gem that implements the same HMAC verification?

Thanks!

**Comment by alexagranov** [comment]
As @dblock pointed out, it's probably more appropriate to add a request validation helper in the repo that actually receives requests - slack-ruby-bot or slack-ruby-bot-server - but since you're asking here...

If your registered endpoint is something like `/events` and you're running a Sinatra server, you could do something like:

```
# Events API endpoint
post '/events' do
  body = ActiveSupport::JSON.decode(request.body.read)&.deep_symbolize_keys!
  halt 404 unless valid_token?(body[:token])
  ...
end

def valid_token?(token)
  token == Rails.configuration.x.slack.verification_token
end
```

You may notice that I'm referencing `Rails.configuration` which is possible by init'ing the Rails app via,
```
require ::File.expand_path('../config/environment', __FILE__)
```
from your rackup .ru file.  You could also just basic Sinatra configuration for your verification token - I just happen to run slack-bot servers in tandem with a Rails app and wanted to share the same config.

Note that the token will be in `params` for slash command and action callback endpoints, the events API endpoint is yet another endpoint.

**Comment by dblock** [comment]
Again, I would take a PR along these lines.

**Comment by dblock** [comment]
Needed this in [slack-strava](https://github.com/dblock/slack-strava), so took a stab at it in https://github.com/slack-ruby/slack-ruby-client/pull/245.
