### ISSUE TITLE
Legacy Tokens may no longer be generatable

### ISSUE THREAD

**Issue by eldondevat** [slack-ruby/slack-ruby-client#372]
It seems that new legacy tokens can't be generated any more, as described [here](https://github.com/slack-ruby/slack-ruby-client/tree/ebf98319cf9d89ad4e75dbca0ae8ecf94a855aa3#using-the-legacy-api-token). 
Am I correctly interpreting this message from [this page]
(https://api.slack.com/legacy/custom-integrations/legacy-tokens#token-mgmt)? 
![image](https://user-images.githubusercontent.com/31245140/112157690-dbf0c000-8bbd-11eb-85bf-f2e371da5f5e.png)

**Comment by wasabigeek** [comment]
Feel free to submit a PR to correct the docs!

**Comment by eldondevat** [comment]
@wasabigeek Are you able to confirm this is also the behavior of your slack account?

**Comment by wasabigeek** [comment]
I am seeing the same in my test account, which was created sometime last year (I don't think I was able to create it then either), as well as the bot we use at work (which is still on a legacy token, but created a few years ago).

**Comment by Buzzkill-McSquare** [comment]
It might be worth bringing this up again, as the CLI requires the use of tokens that can no longer be generated.

**Comment by nello** [comment]
It looks like the whole library now has no working examples, at least as far as I can see. This appears to be a dead project.

**Comment by dblock** [comment]
> It looks like the whole library now has no working examples, at least as far as I can see. This appears to be a dead project.

The library is alive and well, but the CLI documentation needs to be updated. The CLI also has a faraday incompatibility that was fixed in #434 and needs to be released (2.1.0) that I can do soon. I believe https://api.slack.com/tutorials/tracks/getting-a-token is the new/current way for getting a token, but I haven't tried - we also could extend samples to require an app token and generate a user token by authorizing a user.

@nello Why don't you help us update the docs?
