### ISSUE TITLE
Do I really need to instantiate a listening app to fire off a DM to Slack?

### ISSUE THREAD

**Issue by jmcdonagh** [slack-ruby/slack-ruby-client#384]
Hi, I'm trying to just create a tiny program for occasional use that allows developers to send DMs of arbitrary text to people. Just a simple script that sends a DM to a target. Do I really need to set up an app that listens, create event subscriptions, etc? This is just a one way, fire it off kind of thing and the example code I see all references setting up an actual two-way bot.

**Comment by dblock** [comment]
The samples are for those realtime apps because doing what you're trying to do is that simple. See https://github.com/slack-ruby/slack-ruby-client#web-client-examples for how to get started. You'll need to obtain a token from slack that lets you send DMs and then it's a 1-liner.

**Comment by dblock** [comment]
So it sound like it wants you to boot an entire app and do oauth and then you get a token to use? That seems wrong. As you said you don't want to have a multi-tenet application, you just want to post to a channel. I would do more research or ask someone at Slack about it before trying to go this route.

Otherwise, I've faced a similar problem in https://github.com/dblock/strava-ruby-client where it wanted to do the oauth dance to get a token. I worked around it by writing a command line client that would do it for me (https://github.com/dblock/strava-ruby-cli#authentication). That's the only other thing I can think of.
